#!/usr/bin/env python3
"""
plot_tissue2d_figures.py — Plot 2D tissue simulation results
Reproduces Appendix Fig A2 from Sato et al. (2025).

Reads CSV data from tissue2d_tauf_qtv.csv and tissue2d_u_qtv.csv
generated by julia/tissue_armyheart.jl (ArmyHeart/Thunderbolt.jl).

Figures generated:
  fig_tissue2d_tauf_qtvi.png  — QTVi vs τ_f (Fig A2C)
  fig_tissue2d_u_qtvi.png     — QTVi vs u   (Fig A2D)
  fig_tissue2d_ecg.png        — Representative ECG traces (Fig A2B)
  fig_tissue2d_summary.png    — Combined panel
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import os

DATA_DIR = os.path.join(os.path.dirname(__file__), 'data')
OUT_DIR  = os.path.dirname(__file__)

C_STABLE  = '#2ecc71'
C_NEAR    = '#e67e22'
C_ALT     = '#e74c3c'
C_QTV     = '#2c3e50'


def load_csv(name):
    path = os.path.join(DATA_DIR, name)
    if not os.path.exists(path):
        print(f"  WARNING: {name} not found — skipping")
        return None
    return pd.read_csv(path)


def plot_tauf_qtvi():
    df = load_csv('tissue2d_tauf_qtv.csv')
    if df is None: return
    df = df.dropna(subset=['qtvi'])

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
    fig.suptitle('2D Tissue — QT Variability vs τ_f  (Fig A2C)\n'
                 'Sato-Bers model, N_CaL=100,000 stochastic channels',
                 fontsize=12, fontweight='bold')

    # QTVi vs τ_f
    ax1.plot(df['tauf'], df['qtvi'], 'o-', color=C_QTV, lw=2.5, ms=8)
    ax1.axhline(-5.5, color='gray', linestyle='--', alpha=0.5, label='Stable baseline')
    ax1.set_xlabel('τ_f (ms)', fontsize=13)
    ax1.set_ylabel('QTVi = log₁₀[Var(QT)/Mean²(QT)]', fontsize=11)
    ax1.set_title('QTVi rises near alternans onset\n(τ_f ≈ 50–52 ms)', fontsize=11)
    ax1.legend(fontsize=10)
    ax1.grid(alpha=0.3)

    # QT mean ± std vs τ_f
    ax2.errorbar(df['tauf'], df['qt_mean'], yerr=df['qt_std'],
                 fmt='o-', color=C_QTV, lw=2, ms=7, capsize=4, label='QT mean ± std')
    ax2.set_xlabel('τ_f (ms)', fontsize=13)
    ax2.set_ylabel('QT interval (ms)', fontsize=12)
    ax2.set_title('QT mean and variability vs τ_f', fontsize=11)
    ax2.legend(fontsize=10); ax2.grid(alpha=0.3)

    plt.tight_layout()
    out = os.path.join(OUT_DIR, 'fig_tissue2d_tauf_qtvi.png')
    plt.savefig(out, dpi=150, bbox_inches='tight')
    print(f'  Saved: {out}')
    plt.close()


def plot_u_qtvi():
    df = load_csv('tissue2d_u_qtv.csv')
    if df is None: return
    df = df.dropna(subset=['qtvi'])

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
    fig.suptitle('2D Tissue — QT Variability vs u  (Fig A2D)\n'
                 'Ca²⁺-driven instability (τ_f=35 ms, varied u)',
                 fontsize=12, fontweight='bold')

    ax1.plot(df['u'], df['qtvi'], 's-', color='#8e44ad', lw=2.5, ms=8)
    ax1.set_xlabel('u (ms⁻¹)', fontsize=13)
    ax1.set_ylabel('QTVi', fontsize=12)
    ax1.set_title('QTVi rises as Ca²⁺ instability increases', fontsize=11)
    ax1.grid(alpha=0.3)

    ax2.errorbar(df['u'], df['qt_mean'], yerr=df['qt_std'],
                 fmt='s-', color='#8e44ad', lw=2, ms=7, capsize=4)
    ax2.set_xlabel('u (ms⁻¹)', fontsize=13)
    ax2.set_ylabel('QT interval (ms)', fontsize=12)
    ax2.set_title('QT mean and variability vs u', fontsize=11)
    ax2.grid(alpha=0.3)

    plt.tight_layout()
    out = os.path.join(OUT_DIR, 'fig_tissue2d_u_qtvi.png')
    plt.savefig(out, dpi=150, bbox_inches='tight')
    print(f'  Saved: {out}')
    plt.close()


def plot_ecg_traces():
    df = load_csv('tissue2d_ecg_traces.csv')
    if df is None: return

    t_ms = df['t_ms'].values
    ecg_cols = [c for c in df.columns if c != 't_ms']

    colors = {'tauf30': C_STABLE, 'tauf45': C_NEAR, 'tauf52': C_ALT,
              'u3.0': C_STABLE, 'u8.0': C_NEAR, 'u9.5': C_ALT}
    labels = {'tauf30': 'τ_f=30ms (stable)', 'tauf45': 'τ_f=45ms (near onset)',
              'tauf52': 'τ_f=52ms (alternans)', 'u3.0': 'u=3 (stable)',
              'u8.0': 'u=8 (near onset)', 'u9.5': 'u=9.5 (Ca²⁺ alternans)'}

    fig, axes = plt.subplots(len(ecg_cols), 1, figsize=(12, 3*len(ecg_cols)))
    if len(ecg_cols) == 1: axes = [axes]
    fig.suptitle('2D Tissue Pseudo-ECG Traces (Plonsey 1964)  —  Fig A2B',
                 fontsize=13, fontweight='bold')

    for ax, col in zip(axes, ecg_cols):
        color = colors.get(col, 'steelblue')
        label = labels.get(col, col)
        # Show last 3 beats
        n = len(t_ms)
        show = max(0, n - 3*round(300/0.05, 0).__int__())
        ax.plot(t_ms[show:], df[col].values[show:], color=color, lw=1.2, label=label)
        ax.set_ylabel('φₑ (arb.)', fontsize=10)
        ax.legend(loc='upper right', fontsize=10)
        ax.grid(alpha=0.2)

    axes[-1].set_xlabel('Time (ms)', fontsize=12)
    plt.tight_layout()
    out = os.path.join(OUT_DIR, 'fig_tissue2d_ecg.png')
    plt.savefig(out, dpi=150, bbox_inches='tight')
    print(f'  Saved: {out}')
    plt.close()


def plot_summary():
    df_tauf = load_csv('tissue2d_tauf_qtv.csv')
    df_u    = load_csv('tissue2d_u_qtv.csv')
    if df_tauf is None and df_u is None:
        print("  No data found — skipping summary")
        return

    fig = plt.figure(figsize=(14, 6))
    gs  = gridspec.GridSpec(1, 2, figure=fig, wspace=0.35)
    fig.suptitle('2D Tissue Simulation  —  Appendix Fig A2 (Sato et al. 2025)\n'
                 'Stochastic ICaL gating (N_CaL=100,000), ArmyHeart/Thunderbolt.jl',
                 fontsize=12, fontweight='bold')

    if df_tauf is not None:
        df_t = df_tauf.dropna(subset=['qtvi'])
        ax1 = fig.add_subplot(gs[0])
        ax1.plot(df_t['tauf'], df_t['qtvi'], 'o-', color=C_QTV, lw=2.5, ms=8)
        ax1.set_xlabel('τ_f (ms)', fontsize=13)
        ax1.set_ylabel('QTVi', fontsize=13)
        ax1.set_title('QTVi vs τ_f\n(voltage-driven instability)', fontsize=12)
        ax1.grid(alpha=0.3)
        # Annotate onset
        if len(df_t) > 3:
            idx_max = df_t['qtvi'].idxmax()
            tf_max  = df_t.loc[idx_max, 'tauf']
            qt_max  = df_t.loc[idx_max, 'qtvi']
            ax1.annotate(f'Onset\n~{tf_max}ms',
                         xy=(tf_max, qt_max), xytext=(tf_max-8, qt_max+0.5),
                         arrowprops=dict(arrowstyle='->', color='gray'),
                         fontsize=9)

    if df_u is not None:
        df_u2 = df_u.dropna(subset=['qtvi'])
        ax2 = fig.add_subplot(gs[1])
        ax2.plot(df_u2['u'], df_u2['qtvi'], 's-', color='#8e44ad', lw=2.5, ms=8)
        ax2.set_xlabel('u (ms⁻¹)', fontsize=13)
        ax2.set_ylabel('QTVi', fontsize=13)
        ax2.set_title('QTVi vs u\n(Ca²⁺-driven instability)', fontsize=12)
        ax2.grid(alpha=0.3)

    plt.tight_layout(rect=[0, 0, 1, 0.93])
    out = os.path.join(OUT_DIR, 'fig_tissue2d_summary.png')
    plt.savefig(out, dpi=150, bbox_inches='tight')
    print(f'  Saved: {out}')
    plt.close()


if __name__ == '__main__':
    print('Plotting 2D tissue figures...')
    os.makedirs(OUT_DIR, exist_ok=True)
    plot_tauf_qtvi()
    plot_u_qtvi()
    plot_ecg_traces()
    plot_summary()
    print('\nDone. Run julia/tissue_armyheart.jl to generate the data first.')
