"""
plot_figures.py — Reproduce key figures from Sato et al. (2025) QTVI paper.

Reads CSV data generated by figures/generate_figure_data.jl and produces:
  - fig1_stability_boundary.png  : Stability map (tauf vs u)
  - fig2_tauf_sweep.png          : APD variability + bifurcation vs tauf (Fig 2/4A)
  - fig3_u_sweep.png             : Ca2+ variability + bifurcation vs u (Fig 3/4B/4C)
  - fig4_ap_traces.png           : Action potential traces at representative tauf values
  - fig5_apd_per_beat.png        : APD vs beat number for selected tauf (Fig 2B)
  - fig6_ca_per_beat.png         : Ca2+ transient peak vs beat (Fig 3B)

All figures use a clean publication-style layout matching the paper.

References:
    Sato D et al. J Physiol (2025).
    DOI: 10.1113/JP289051
"""

import csv
import os
import sys
import math
from collections import defaultdict

import numpy as np
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend for headless generation
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.lines import Line2D

# --- Style settings ---
plt.rcParams.update({
    'font.size': 10,
    'axes.labelsize': 11,
    'axes.titlesize': 11,
    'legend.fontsize': 9,
    'xtick.labelsize': 9,
    'ytick.labelsize': 9,
    'figure.dpi': 150,
    'lines.linewidth': 1.5,
    'axes.spines.top': False,
    'axes.spines.right': False,
})

DATA_DIR = os.path.join(os.path.dirname(__file__), 'data')
OUT_DIR  = os.path.dirname(__file__)

def load_csv(filename):
    """Load CSV file into list of dicts with float values."""
    with open(os.path.join(DATA_DIR, filename)) as f:
        reader = csv.DictReader(f)
        return [{k: float(v) for k, v in row.items()} for row in reader]


# =============================================================================
# Figure 2 / 4A — APD bifurcation diagram + variability vs tauf
# =============================================================================
def fig_tauf_sweep():
    """
    Reproduce Fig 2A and Fig 4A (top + bottom) from Sato et al. 2025.

    Panel A (top): APD bifurcation diagram — scatter of APD min and max vs tauf.
      Shows period-doubling (alternans) above a critical tauf value.
    Panel B (middle): APD variability (std) vs tauf — every beat (black) and
      every-other-beat (red). Shows variability peak at onset of alternans.
    Panel C (bottom): APD mean vs tauf — shows lengthening then shortening
      as alternans progresses.
    """
    data = load_csv('tauf_sweep.csv')
    tauf    = [r['tauf']         for r in data]
    apd_mu  = [r['apd_mean']     for r in data]
    apd_sig = [r['apd_std']      for r in data]
    apd_min = [r['apd_min']      for r in data]
    apd_max = [r['apd_max']      for r in data]
    apd_alt = [r['apd_std_altbeat'] for r in data]
    ca_mu   = [r['ca_mean']      for r in data]
    ca_sig  = [r['ca_std']       for r in data]
    ca_min  = [r['ca_min']       for r in data]
    ca_max  = [r['ca_max']       for r in data]

    fig, axes = plt.subplots(3, 1, figsize=(7, 8), sharex=True)

    # --- Panel A: Bifurcation diagram ---
    ax = axes[0]
    ax.scatter(tauf, apd_min, s=8, c='steelblue', alpha=0.7, label='APD min/max')
    ax.scatter(tauf, apd_max, s=8, c='steelblue', alpha=0.7)
    ax.set_ylabel('APD (ms)')
    ax.set_title('APD Bifurcation Diagram (tauf sweep, u = 3.0)')
    ax.legend([Line2D([0],[0],marker='o',color='w',markerfacecolor='steelblue',
                      markersize=5)], ['APD scatter (min/max)'], loc='upper left')

    # Mark onset of alternans (where APD_max - APD_min > 5 ms)
    for i, (lo, hi, tf) in enumerate(zip(apd_min, apd_max, tauf)):
        if hi - lo > 5.0:
            ax.axvline(tf, color='royalblue', linestyle='--', alpha=0.5, linewidth=1)
            ax.annotate('alternans\nonset', xy=(tf, max(apd_max)*0.7),
                        fontsize=8, color='royalblue', ha='center')
            break

    # --- Panel B: APD variability ---
    ax = axes[1]
    ax.plot(tauf, apd_sig, 'k-o', markersize=3, label='Every beat (std)')
    ax.plot(tauf, apd_alt, 'r--s', markersize=3, label='Every other beat (std)')
    ax.set_ylabel('APD variability (ms)')
    ax.set_title('APD Variability vs τ_f')
    ax.legend(loc='upper left')

    # --- Panel C: Ca2+ peak ---
    ax = axes[2]
    ax.scatter(tauf, ca_min, s=8, c='firebrick', alpha=0.7)
    ax.scatter(tauf, ca_max, s=8, c='firebrick', alpha=0.7)
    ax.set_ylabel('[Ca²⁺]_i peak (µM)')
    ax.set_xlabel('τ_f (ms; LTCC recovery)')
    ax.set_title('[Ca²⁺]_i Peak Bifurcation')

    plt.tight_layout()
    outfile = os.path.join(OUT_DIR, 'fig2_tauf_sweep.png')
    fig.savefig(outfile, bbox_inches='tight')
    plt.close(fig)
    print(f'Saved: {outfile}')


# =============================================================================
# Figure 3 / 4B/4C — u sweep (I-clamp and AP-clamp)
# =============================================================================
def fig_u_sweep():
    """
    Reproduce Figs 3 and 4B/4C from Sato et al. 2025.

    Shows how increasing u (SR Ca2+ release steepness) drives:
    - Ca2+ transient alternans in AP-clamp mode (Fig 4B)
    - APD alternans and variability in current-clamp mode (Fig 4C)
    """
    iclamp = load_csv('u_sweep_iclamp.csv')
    apclamp = load_csv('u_sweep_apclamp.csv')

    u_ic   = [r['u']               for r in iclamp]
    apd_ic = [r['apd_mean']        for r in iclamp]
    sig_ic = [r['apd_std']         for r in iclamp]
    alt_ic = [r['apd_std_altbeat'] for r in iclamp]
    ca_ic  = [r['ca_mean']         for r in iclamp]
    lo_ic  = [r['apd_min']         for r in iclamp]
    hi_ic  = [r['apd_max']         for r in iclamp]

    u_ap   = [r['u']               for r in apclamp]
    ca_ap  = [r['ca_mean']         for r in apclamp]
    sig_ap = [r['ca_std']          for r in apclamp]
    alt_ap = [r['ca_std_altbeat']  for r in apclamp]
    lo_ap  = [r['ca_min']          for r in apclamp]
    hi_ap  = [r['ca_max']          for r in apclamp]

    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    fig.suptitle('u sweep: Ca²⁺-driven Instability (τ_f = 35 ms)', fontsize=12)

    # Top-left: Ca2+ bifurcation (AP-clamp) — Fig 4B top
    ax = axes[0, 0]
    ax.scatter(u_ap, lo_ap, s=8, c='firebrick', alpha=0.7)
    ax.scatter(u_ap, hi_ap, s=8, c='firebrick', alpha=0.7)
    ax.set_title('[Ca²⁺]_i peak (AP-clamp)')
    ax.set_ylabel('[Ca²⁺]_i peak (µM)')
    ax.set_xlabel('u (SR Ca²⁺ gain)')
    for i, (lo, hi, u) in enumerate(zip(lo_ap, hi_ap, u_ap)):
        if hi - lo > 0.05:
            ax.axvline(u, color='firebrick', linestyle='--', alpha=0.5, linewidth=1)
            ax.annotate('Ca²⁺\nalternans', xy=(u, max(hi_ap)*0.55),
                        fontsize=8, color='firebrick', ha='center')
            break

    # Top-right: Ca2+ variability (AP-clamp) — Fig 3A / 4B bottom
    ax = axes[0, 1]
    ax.plot(u_ap, sig_ap, 'k-o', markersize=3, label='Every beat (std)')
    ax.plot(u_ap, alt_ap, 'r--s', markersize=3, label='Every other beat (std)')
    ax.set_title('[Ca²⁺]_i Variability (AP-clamp)')
    ax.set_ylabel('[Ca²⁺]_i variability (µM)')
    ax.set_xlabel('u (SR Ca²⁺ gain)')
    ax.legend(loc='upper left')

    # Bottom-left: APD bifurcation (I-clamp) — Fig 4C top
    ax = axes[1, 0]
    ax.scatter(u_ic, lo_ic, s=8, c='steelblue', alpha=0.7)
    ax.scatter(u_ic, hi_ic, s=8, c='steelblue', alpha=0.7)
    ax.set_title('APD (I-clamp)')
    ax.set_ylabel('APD (ms)')
    ax.set_xlabel('u (SR Ca²⁺ gain)')
    for i, (lo, hi, u) in enumerate(zip(lo_ic, hi_ic, u_ic)):
        if hi - lo > 5.0:
            ax.axvline(u, color='steelblue', linestyle='--', alpha=0.5, linewidth=1)
            ax.annotate('APD\nalternans', xy=(u, max(hi_ic)*0.6),
                        fontsize=8, color='steelblue', ha='center')
            break

    # Bottom-right: APD variability (I-clamp) — Fig 3C / 4C bottom
    ax = axes[1, 1]
    ax.plot(u_ic, sig_ic, 'k-o', markersize=3, label='Every beat (std)')
    ax.plot(u_ic, alt_ic, 'r--s', markersize=3, label='Every other beat (std)')
    ax.set_title('APD Variability (I-clamp)')
    ax.set_ylabel('APD variability (ms)')
    ax.set_xlabel('u (SR Ca²⁺ gain)')
    ax.legend(loc='upper left')

    plt.tight_layout()
    outfile = os.path.join(OUT_DIR, 'fig3_u_sweep.png')
    fig.savefig(outfile, bbox_inches='tight')
    plt.close(fig)
    print(f'Saved: {outfile}')


# =============================================================================
# Figure: Action Potential + Ca2+ Transient Traces
# =============================================================================
def fig_ap_traces():
    """
    Show action potential and Ca2+ transient at different tauf values.
    Illustrates how increasing tauf prolongs the AP and modifies Ca2+ cycling.
    """
    data = load_csv('ap_traces.csv')
    tauf_vals = sorted(set(int(r['tauf']) for r in data))
    by_tauf = defaultdict(list)
    for r in data:
        by_tauf[int(r['tauf'])].append(r)

    colors = plt.cm.viridis(np.linspace(0, 0.9, len(tauf_vals)))

    fig, axes = plt.subplots(3, 1, figsize=(9, 8), sharex=True)

    for color, tf in zip(colors, tauf_vals):
        rows = by_tauf[tf]
        t  = np.array([r['time'] for r in rows])
        v  = np.array([r['v']    for r in rows])
        ci = np.array([r['ci']   for r in rows])
        d  = np.array([r['d']    for r in rows])
        f  = np.array([r['f']    for r in rows])

        axes[0].plot(t, v, color=color, linewidth=1.2, label=f'τ_f={tf}')
        axes[1].plot(t, ci, color=color, linewidth=1.2)
        axes[2].plot(t, d * f, color=color, linewidth=1.2)  # ICaL open probability ~ d*f

    axes[0].set_ylabel('V_m (mV)')
    axes[0].set_title('Action Potential')
    axes[0].legend(loc='upper right', ncol=3, fontsize=8)
    axes[0].axhline(-70, color='grey', linestyle=':', linewidth=0.8, alpha=0.7)

    axes[1].set_ylabel('[Ca²⁺]_i (µM)')
    axes[1].set_title('Ca²⁺ Transient')

    axes[2].set_ylabel('d·f (open prob.)')
    axes[2].set_xlabel('Time (ms)')
    axes[2].set_title('ICaL Open Probability (d·f)')

    plt.tight_layout()
    outfile = os.path.join(OUT_DIR, 'fig4_ap_traces.png')
    fig.savefig(outfile, bbox_inches='tight')
    plt.close(fig)
    print(f'Saved: {outfile}')


# =============================================================================
# Figure 2B — APD vs beat number (alternans pattern)
# =============================================================================
def fig_apd_per_beat():
    """
    Reproduce Fig 2B from Sato et al. 2025.

    Shows APD vs beat number for several tauf values, illustrating:
    - Periodic (constant) APD at low tauf (stable)
    - Beat-to-beat alternation (2:1) at high tauf (alternans)
    - Stochastic variability visible at intermediate tauf values
    """
    data = load_csv('apd_per_beat.csv')
    tauf_vals = sorted(set(int(r['tauf']) for r in data))
    by_tauf = defaultdict(list)
    for r in data:
        by_tauf[int(r['tauf'])].append(r)

    n = len(tauf_vals)
    nrows = math.ceil(n / 2)
    fig, axes = plt.subplots(nrows, 2, figsize=(10, 3 * nrows), sharey=False)
    if n == 1:
        axes = [[axes]]
    axes = [ax for row in axes for ax in row]

    for i, tf in enumerate(tauf_vals):
        ax = axes[i]
        rows = by_tauf[tf]
        beats = [r['beat'] for r in rows]
        apds  = [r['apd']  for r in rows]
        camx  = [r['camax'] for r in rows]

        ax.plot(beats, apds, 'b-', linewidth=0.8, alpha=0.8)
        ax.set_title(f'τ_f = {tf} ms')
        ax.set_ylabel('APD (ms)')
        ax.set_xlabel('Beat #')

        # Compute and display variability
        arr = np.array(apds)
        std = np.std(arr)
        ax.text(0.97, 0.97, f'std={std:.2f} ms', transform=ax.transAxes,
                ha='right', va='top', fontsize=8, color='navy')

    # Hide unused subplots
    for j in range(len(tauf_vals), len(axes)):
        axes[j].set_visible(False)

    fig.suptitle('APD vs Beat Number at Different τ_f Values\n(u = 3.0, N_CaL = 100,000)',
                 fontsize=11)
    plt.tight_layout()
    outfile = os.path.join(OUT_DIR, 'fig5_apd_per_beat.png')
    fig.savefig(outfile, bbox_inches='tight')
    plt.close(fig)
    print(f'Saved: {outfile}')


# =============================================================================
# Figure 3B — Ca2+ transient per beat (AP-clamp, different u values)
# =============================================================================
def fig_ca_per_beat():
    """
    Reproduce Fig 3B from Sato et al. 2025.

    Shows Ca2+ transient peak vs beat number for different u values under
    AP-clamp. Demonstrates Ca2+ alternans onset as u increases, independent
    of AP variability (since voltage is clamped to a fixed waveform).
    """
    data = load_csv('ca_per_beat_apclamp.csv')
    u_vals = sorted(set(r['u'] for r in data))
    by_u = defaultdict(list)
    for r in data:
        by_u[r['u']].append(r)

    n = len(u_vals)
    fig, axes = plt.subplots(2, 2, figsize=(10, 6))
    axes = [ax for row in axes for ax in row]

    colors = ['steelblue', 'darkorange', 'firebrick', 'purple']
    for i, u_val in enumerate(u_vals):
        ax = axes[i]
        rows = by_u[u_val]
        beats = [r['beat'] for r in rows]
        ca    = [r['camax'] for r in rows]

        ax.plot(beats, ca, color=colors[i % len(colors)], linewidth=0.8)
        ax.set_title(f'u = {u_val} ms⁻¹ (AP-clamp, τ_f = 35 ms)')
        ax.set_ylabel('[Ca²⁺]_i peak (µM)')
        ax.set_xlabel('Beat #')

        arr = np.array(ca)
        std = np.std(arr)
        ax.text(0.97, 0.97, f'std={std:.4f} µM', transform=ax.transAxes,
                ha='right', va='top', fontsize=8, color='black')

    fig.suptitle('Ca²⁺ Transient Peak vs Beat (AP-clamp)\n'
                 'Increasing u drives Ca²⁺ cycling instability', fontsize=11)
    plt.tight_layout()
    outfile = os.path.join(OUT_DIR, 'fig6_ca_per_beat.png')
    fig.savefig(outfile, bbox_inches='tight')
    plt.close(fig)
    print(f'Saved: {outfile}')


# =============================================================================
# Stability boundary (Fig 1) — requires combined tauf + u data
# Build from tauf and u sweep data
# =============================================================================
def fig_stability_boundary():
    """
    Reproduce Fig 1 from Sato et al. 2025 — the stability boundary map.

    The stability boundary separates:
    - Stable region (periodic APs, no alternans)
    - Vm-driven alternans (high tauf, varied u)
    - Ca2+-driven alternans (high u, varied tauf)

    Derived from:
    - tauf_sweep: onset of alternans as a function of tauf (u fixed at 3.0)
    - u_sweep_iclamp: onset of Ca2+ alternans as a function of u (tauf fixed at 35)
    """
    tauf_data = load_csv('tauf_sweep.csv')
    u_data    = load_csv('u_sweep_iclamp.csv')

    # Determine alternans threshold: APD spread > 5 ms
    tauf_alt  = None
    for r in tauf_data:
        if r['apd_max'] - r['apd_min'] > 5.0:
            tauf_alt = r['tauf']
            break

    u_alt = None
    for r in u_data:
        if r['apd_max'] - r['apd_min'] > 5.0:
            u_alt = r['u']
            break

    # Build a rough stability map
    # Points in (tauf, u) space:
    # - From tauf sweep (u=3): mark stable vs alternans
    # - From u sweep (tauf=35): mark stable vs alternans
    tauf_vals  = [r['tauf']  for r in tauf_data]
    spread_t   = [r['apd_max'] - r['apd_min'] for r in tauf_data]

    u_vals     = [r['u']     for r in u_data]
    spread_u   = [r['apd_max'] - r['apd_min'] for r in u_data]
    ca_spread_u = [r['ca_max'] - r['ca_min'] for r in u_data]

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # Left: APD spread vs tauf (at u=3)
    ax = axes[0]
    ax.fill_between(tauf_vals, 0, spread_t, alpha=0.3, color='steelblue',
                    label='APD spread (alternans amplitude)')
    ax.axhline(5, color='red', linestyle='--', linewidth=1, label='Alternans threshold (5 ms)')
    if tauf_alt:
        ax.axvline(tauf_alt, color='royalblue', linestyle=':', linewidth=1.5,
                   label=f'Onset: τ_f = {tauf_alt} ms')
    ax.set_xlabel('τ_f (ms; LTCC recovery)')
    ax.set_ylabel('APD_max - APD_min (ms)')
    ax.set_title('Voltage-Driven Instability\n(u = 3.0, tauf sweep)')
    ax.legend(loc='upper left', fontsize=8)
    ax.set_ylim(bottom=0)

    # Right: APD spread vs u (tauf=35)
    ax = axes[1]
    ax.fill_between(u_vals, 0, spread_u, alpha=0.3, color='darkorange',
                    label='APD spread')
    ax.fill_between(u_vals, 0, ca_spread_u, alpha=0.2, color='firebrick',
                    label='Ca²⁺ spread')
    ax.axhline(5, color='red', linestyle='--', linewidth=1, label='APD alternans threshold')
    if u_alt:
        ax.axvline(u_alt, color='darkorange', linestyle=':', linewidth=1.5,
                   label=f'APD alternans onset: u = {u_alt}')
    ax.set_xlabel('u (SR Ca²⁺ gain, ms⁻¹)')
    ax.set_ylabel('Spread (ms or µM)')
    ax.set_title('Ca²⁺-Driven Instability\n(τ_f = 35 ms, u sweep)')
    ax.legend(loc='upper left', fontsize=8)
    ax.set_ylim(bottom=0)

    plt.tight_layout()
    outfile = os.path.join(OUT_DIR, 'fig1_stability_boundary.png')
    fig.savefig(outfile, bbox_inches='tight')
    plt.close(fig)
    print(f'Saved: {outfile}')


# =============================================================================
# Summary figure combining key panels
# =============================================================================
def fig_summary():
    """
    Create a single comprehensive summary figure showing the main findings.
    This combines the most important panels into one publication-ready figure.
    """
    tauf_data  = load_csv('tauf_sweep.csv')
    u_ic_data  = load_csv('u_sweep_iclamp.csv')
    u_apc_data = load_csv('u_sweep_apclamp.csv')
    beat_data  = load_csv('apd_per_beat.csv')

    tauf  = [r['tauf']      for r in tauf_data]
    apd_std = [r['apd_std'] for r in tauf_data]
    apd_alt = [r['apd_std_altbeat'] for r in tauf_data]
    apd_min = [r['apd_min'] for r in tauf_data]
    apd_max = [r['apd_max'] for r in tauf_data]

    u_ic = [r['u']          for r in u_ic_data]
    apd_std_ic = [r['apd_std'] for r in u_ic_data]
    apd_alt_ic = [r['apd_std_altbeat'] for r in u_ic_data]
    apd_min_ic = [r['apd_min'] for r in u_ic_data]
    apd_max_ic = [r['apd_max'] for r in u_ic_data]

    u_ap = [r['u']          for r in u_apc_data]
    ca_std_ap = [r['ca_std']  for r in u_apc_data]
    ca_alt_ap = [r['ca_std_altbeat'] for r in u_apc_data]
    ca_min_ap = [r['ca_min']  for r in u_apc_data]
    ca_max_ap = [r['ca_max']  for r in u_apc_data]

    # Beat traces for tauf=52, 57 (near bifurcation)
    by_tauf = defaultdict(list)
    for r in beat_data:
        by_tauf[int(r['tauf'])].append(r)

    fig = plt.figure(figsize=(14, 10))
    gs  = gridspec.GridSpec(3, 3, figure=fig, hspace=0.45, wspace=0.35)

    # ---- Row 0 ----
    # (0,0): APD bifurcation vs tauf
    ax00 = fig.add_subplot(gs[0, 0])
    ax00.scatter(tauf, apd_min, s=5, c='steelblue', alpha=0.7)
    ax00.scatter(tauf, apd_max, s=5, c='steelblue', alpha=0.7)
    ax00.set_ylabel('APD (ms)')
    ax00.set_xlabel('τ_f (ms)')
    ax00.set_title('APD bifurcation (tauf sweep)\nu = 3.0')
    for tf, lo, hi in zip(tauf, apd_min, apd_max):
        if hi - lo > 5:
            ax00.axvline(tf, color='royalblue', linestyle='--', alpha=0.4, lw=1)
            ax00.annotate('↑ alternans', xy=(tf+0.5, (max(apd_max)+min(apd_min))/2),
                          fontsize=7, color='royalblue')
            break

    # (0,1): APD variability vs tauf
    ax01 = fig.add_subplot(gs[0, 1])
    ax01.plot(tauf, apd_std, 'k-', lw=1.2, label='every beat')
    ax01.plot(tauf, apd_alt, 'r--', lw=1.2, label='every other beat')
    ax01.set_ylabel('APD std (ms)')
    ax01.set_xlabel('τ_f (ms)')
    ax01.set_title('APD Variability vs τ_f\n(≈ Fig 2A)')
    ax01.legend(fontsize=8)

    # (0,2): APD vs beat number for tauf=52 and tauf=57
    ax02 = fig.add_subplot(gs[0, 2])
    colors_t = ['steelblue', 'firebrick']
    for color, tf in zip(colors_t, [52, 57]):
        if tf in by_tauf:
            rows = by_tauf[tf]
            beats = [r['beat'] for r in rows]
            apds  = [r['apd']  for r in rows]
            ax02.plot(beats, apds, color=color, lw=0.8, alpha=0.8, label=f'τ_f={tf}')
    ax02.set_ylabel('APD (ms)')
    ax02.set_xlabel('Beat #')
    ax02.set_title('APD vs Beat # (≈ Fig 2B)')
    ax02.legend(fontsize=8)

    # ---- Row 1 ----
    # (1,0): APD bifurcation vs u (I-clamp)
    ax10 = fig.add_subplot(gs[1, 0])
    ax10.scatter(u_ic, apd_min_ic, s=5, c='steelblue', alpha=0.7)
    ax10.scatter(u_ic, apd_max_ic, s=5, c='steelblue', alpha=0.7)
    ax10.set_ylabel('APD (ms)')
    ax10.set_xlabel('u (SR Ca²⁺ gain)')
    ax10.set_title('APD bifurcation (u sweep)\nτ_f = 35 ms, I-clamp')
    for u_, lo, hi in zip(u_ic, apd_min_ic, apd_max_ic):
        if hi - lo > 5:
            ax10.axvline(u_, color='royalblue', linestyle='--', alpha=0.4, lw=1)
            ax10.annotate('↑', xy=(u_, lo), fontsize=10, color='royalblue', ha='center')
            break

    # (1,1): APD variability vs u (I-clamp)
    ax11 = fig.add_subplot(gs[1, 1])
    ax11.plot(u_ic, apd_std_ic, 'k-', lw=1.2, label='every beat')
    ax11.plot(u_ic, apd_alt_ic, 'r--', lw=1.2, label='every other beat')
    ax11.set_ylabel('APD std (ms)')
    ax11.set_xlabel('u (SR Ca²⁺ gain)')
    ax11.set_title('APD Variability vs u\n(≈ Fig 3C / 4C bottom)')
    ax11.legend(fontsize=8)

    # (1,2): Ca2+ bifurcation vs u (AP-clamp)
    ax12 = fig.add_subplot(gs[1, 2])
    ax12.scatter(u_ap, ca_min_ap, s=5, c='firebrick', alpha=0.7)
    ax12.scatter(u_ap, ca_max_ap, s=5, c='firebrick', alpha=0.7)
    ax12.set_ylabel('[Ca²⁺]_i peak (µM)')
    ax12.set_xlabel('u (SR Ca²⁺ gain)')
    ax12.set_title('[Ca²⁺]_i bifurcation\nτ_f = 35 ms, AP-clamp')
    for u_, lo, hi in zip(u_ap, ca_min_ap, ca_max_ap):
        if hi - lo > 0.05:
            ax12.axvline(u_, color='firebrick', linestyle='--', alpha=0.4, lw=1)
            ax12.annotate('↑', xy=(u_, lo), fontsize=10, color='firebrick', ha='center')
            break

    # ---- Row 2 ----
    # (2,0): Ca2+ variability vs u (AP-clamp)
    ax20 = fig.add_subplot(gs[2, 0])
    ax20.plot(u_ap, ca_std_ap, 'k-', lw=1.2, label='every beat')
    ax20.plot(u_ap, ca_alt_ap, 'r--', lw=1.2, label='every other beat')
    ax20.set_ylabel('[Ca²⁺] std (µM)')
    ax20.set_xlabel('u (SR Ca²⁺ gain)')
    ax20.set_title('[Ca²⁺] Variability vs u\n(≈ Fig 3A / 4B bottom)')
    ax20.legend(fontsize=8)

    # (2,1): APD std vs tauf (combined color: stable vs alternans)
    ax21 = fig.add_subplot(gs[2, 1])
    tauf_arr = np.array(tauf)
    std_arr  = np.array(apd_std)
    # Find alternans onset
    onset_tf = None
    for tf, lo, hi in zip(tauf, apd_min, apd_max):
        if hi - lo > 5:
            onset_tf = tf
            break
    mask_stable = tauf_arr < (onset_tf if onset_tf else 100)
    ax21.fill_between(tauf_arr[mask_stable], 0, std_arr[mask_stable],
                      color='steelblue', alpha=0.3, label='Stable (periodic)')
    ax21.fill_between(tauf_arr[~mask_stable], 0, std_arr[~mask_stable],
                      color='firebrick', alpha=0.3, label='Alternans')
    ax21.plot(tauf, apd_std, 'k-', lw=1.2)
    if onset_tf:
        ax21.axvline(onset_tf, color='grey', linestyle='--', lw=1,
                     label=f'Onset τ_f={onset_tf}')
    ax21.set_ylabel('APD std (ms)')
    ax21.set_xlabel('τ_f (ms)')
    ax21.set_title('APD Variability (shaded by regime)\n(≈ Fig 2A)')
    ax21.legend(fontsize=7)

    # (2,2): Schematic stability map (tauf vs u)
    ax22 = fig.add_subplot(gs[2, 2])
    # Draw stability regions as text annotations
    ax22.set_xlim(20, 65)
    ax22.set_ylim(2, 12)
    ax22.fill_betweenx([2, 12], 20, onset_tf if onset_tf else 52, alpha=0.15,
                        color='steelblue')
    ax22.fill_betweenx([2, 12], onset_tf if onset_tf else 52, 65, alpha=0.15,
                        color='firebrick')

    # u_alt line (approximate from data)
    u_alt_val = None
    for u_, lo, hi in zip(u_ic, apd_min_ic, apd_max_ic):
        if hi - lo > 5:
            u_alt_val = u_
            break

    if u_alt_val:
        ax22.axhline(u_alt_val, color='darkorange', linestyle='--', lw=1.5, alpha=0.7)
        ax22.text(22, u_alt_val + 0.15, f'Ca²⁺ alternans\nonset u≈{u_alt_val}',
                  fontsize=7, color='darkorange')

    ax22.text(27, 4, 'Stable\n(periodic APs)', fontsize=9, color='steelblue', va='bottom')
    ax22.text(onset_tf+1 if onset_tf else 54, 10.5, 'Vm-driven\nalternans',
              fontsize=8, color='firebrick')
    ax22.text(27, 11, 'Ca²⁺-driven\nalternans', fontsize=8, color='darkorange')

    ax22.set_xlabel('τ_f (ms; LTCC recovery)')
    ax22.set_ylabel('u (RyR SR Ca²⁺ gain)')
    ax22.set_title('Stability Boundary\n(≈ Fig 1)')

    fig.suptitle('Sato et al. 2025 — Key Figures Reproduction\n'
                 'Sato-Bers Cardiac Myocyte Model (N_CaL = 100,000)',
                 fontsize=12, fontweight='bold', y=1.01)

    outfile = os.path.join(OUT_DIR, 'fig0_summary.png')
    fig.savefig(outfile, bbox_inches='tight')
    plt.close(fig)
    print(f'Saved: {outfile}')


# =============================================================================
# Figure 7 — Tissue vs Single-Cell APD Variability + QTVI
# =============================================================================
def fig_tissue_variability():
    """
    Tissue coupling reduces APD variability (electrotonic averaging).
    QTVI rises sharply as alternans bifurcation is approached.

    Panels:
      A (left):  APD std vs tauf — single cell (blue) vs tissue (orange)
      B (middle): APD mean vs tauf — single cell vs tissue
      C (right): QTVI vs tauf — shows diagnostic value of pseudo-ECG
    """
    data = load_csv('tissue_apd_variability.csv')

    tauf     = [r['tauf']         for r in data]
    sc_mean  = [r['sc_apd_mean']  for r in data]
    sc_std   = [r['sc_apd_std']   for r in data]
    tis_mean = [r['tis_apd_mean'] for r in data]
    tis_std  = [r['tis_apd_std']  for r in data]
    qt_mean  = [r['qt_mean']      for r in data]
    qt_std   = [r['qt_std']       for r in data]
    qtvi     = [r['qtvi']         for r in data]

    # Mask NaN
    valid_mask = [not (np.isnan(m) or np.isnan(s))
                  for m, s in zip(tis_mean, tis_std)]
    tauf_v     = [tauf[i]     for i in range(len(tauf)) if valid_mask[i]]
    tis_mean_v = [tis_mean[i] for i in range(len(tauf)) if valid_mask[i]]
    tis_std_v  = [tis_std[i]  for i in range(len(tauf)) if valid_mask[i]]

    fig, axes = plt.subplots(1, 3, figsize=(14, 4))
    fig.suptitle('Tissue Coupling Reduces APD Variability (1D Cable, N=100 cells, D=0.1 mm²/ms)',
                 fontsize=11, fontweight='bold')

    # Panel A: APD std comparison
    ax = axes[0]
    ax.plot(tauf, sc_std, 'bo-', markersize=5, linewidth=1.5, label='Single cell')
    ax.plot(tauf_v, tis_std_v, 's-', color='darkorange', markersize=5,
            linewidth=1.5, label='Tissue (mid-cell)')
    ax.set_xlabel('τ_f (ms; LTCC recovery)')
    ax.set_ylabel('APD std (ms)')
    ax.set_title('APD Variability: Single Cell vs Tissue\n(N_CaL=100,000, BCL=300 ms)')
    ax.legend(loc='upper left')
    ax.set_ylim(bottom=0)
    # Mark alternans onset
    for tf, sc_s in zip(tauf, sc_std):
        if sc_s > 5.0:
            ax.axvline(tf, color='grey', linestyle='--', alpha=0.5, lw=1)
            ax.annotate('↑ alternans\nonset', xy=(tf + 0.3, max(sc_std) * 0.6),
                        fontsize=7.5, color='grey')
            break

    # Panel B: APD mean comparison
    ax = axes[1]
    ax.plot(tauf, sc_mean, 'bo-', markersize=5, linewidth=1.5, label='Single cell')
    ax.plot(tauf_v, tis_mean_v, 's-', color='darkorange', markersize=5,
            linewidth=1.5, label='Tissue (mid-cell)')
    ax.set_xlabel('τ_f (ms; LTCC recovery)')
    ax.set_ylabel('Mean APD (ms)')
    ax.set_title('Mean APD: Single Cell vs Tissue')
    ax.legend(loc='upper left')
    ax.annotate('Electrotonic\ncoupling shortens\neffective APD',
                xy=(0.05, 0.25), xycoords='axes fraction',
                fontsize=8, color='darkorange',
                bbox=dict(boxstyle='round,pad=0.3', facecolor='wheat', alpha=0.5))

    # Panel C: QTVI vs tauf
    ax = axes[2]
    ax.plot(tauf, qtvi, 'k^-', markersize=6, linewidth=1.5, label='QTVI (paced)')
    ax.set_xlabel('τ_f (ms; LTCC recovery)')
    ax.set_ylabel('QTVI')
    ax.set_title('QT Variability Index vs τ_f\n(from pseudo-ECG, constant BCL)')
    # Shade stable vs alternans regions
    qtvi_arr = np.array(qtvi)
    tauf_arr = np.array(tauf)
    thresh = 8.0   # approximate QTVI threshold separating regimes
    ax.axhline(thresh, color='red', linestyle='--', alpha=0.5, lw=1,
               label=f'QTVI={thresh} (onset threshold)')
    ax.fill_between(tauf_arr, -15, qtvi_arr,
                    where=(qtvi_arr < thresh), alpha=0.15, color='steelblue',
                    label='Stable regime')
    ax.fill_between(tauf_arr, -15, qtvi_arr,
                    where=(qtvi_arr >= thresh), alpha=0.15, color='firebrick',
                    label='Alternans regime')
    ax.set_ylim(bottom=min(qtvi) - 0.5)
    ax.legend(loc='lower right', fontsize=7)

    plt.tight_layout()
    outfile = os.path.join(OUT_DIR, 'fig7_tissue_variability.png')
    fig.savefig(outfile, bbox_inches='tight')
    plt.close(fig)
    print(f'Saved: {outfile}')


# =============================================================================
# Figure 8 — Pseudo-ECG traces + Cable propagation snapshot
# =============================================================================
def fig_tissue_ecg():
    """
    Pseudo-ECG from 1D cable simulation (Plonsey 1964 far-field formula).

    Panel A (top-left):   ECG trace — stable regime (tauf=30 ms)
    Panel B (top-right):  ECG trace — near alternans (tauf=52 ms)
    Panel C (bottom):     Cable voltage snapshot — AP propagation at tauf=40 ms
    """
    fig = plt.figure(figsize=(14, 8))
    gs  = gridspec.GridSpec(2, 2, figure=fig, hspace=0.42, wspace=0.35)

    # --- ECG stable (tauf=30) ---
    ecg30_path = os.path.join(DATA_DIR, 'tissue_ecg_tauf30.csv')
    if os.path.exists(ecg30_path):
        ecg30 = load_csv('tissue_ecg_tauf30.csv')
        t30   = [r['t_ms']  for r in ecg30]
        e30   = [r['ecg_mV'] for r in ecg30]
        ax = fig.add_subplot(gs[0, 0])
        ax.plot(t30, e30, 'steelblue', lw=1.2)
        ax.axhline(0, color='grey', lw=0.5, ls=':')
        ax.set_xlabel('Time (ms)')
        ax.set_ylabel('Pseudo-ECG (mV)')
        ax.set_title('Pseudo-ECG — Stable regime\n(τ_f = 30 ms, BCL = 300 ms)')
        # Annotate QRS and T wave
        e_arr = np.array(e30)
        ax.annotate('QRS', xy=(t30[np.argmax(np.abs(e_arr[:100]))], e_arr[:100].max()),
                    xytext=(15, e_arr.max() * 1.1),
                    fontsize=8, color='steelblue',
                    arrowprops=dict(arrowstyle='->', color='steelblue', lw=0.8))

    # --- ECG near alternans (tauf=52) ---
    ecg52_path = os.path.join(DATA_DIR, 'tissue_ecg_tauf52.csv')
    if os.path.exists(ecg52_path):
        ecg52 = load_csv('tissue_ecg_tauf52.csv')
        t52   = [r['t_ms']   for r in ecg52]
        e52   = [r['ecg_mV'] for r in ecg52]
        ax = fig.add_subplot(gs[0, 1])
        ax.plot(t52, e52, 'firebrick', lw=1.2)
        ax.axhline(0, color='grey', lw=0.5, ls=':')
        ax.set_xlabel('Time (ms)')
        ax.set_ylabel('Pseudo-ECG (mV)')
        ax.set_title('Pseudo-ECG — Near alternans\n(τ_f = 52 ms, BCL = 300 ms)')
        ax.annotate('QTVI elevated\n(high variability)', xy=(0.6, 0.85),
                    xycoords='axes fraction', fontsize=8.5, color='firebrick',
                    bbox=dict(boxstyle='round,pad=0.3', facecolor='mistyrose', alpha=0.7))

    # --- Cable propagation snapshot ---
    snap_path = os.path.join(DATA_DIR, 'tissue_cable_snapshot.csv')
    if os.path.exists(snap_path):
        snap = load_csv('tissue_cable_snapshot.csv')
        x_mm = [r['x_mm'] for r in snap]

        # Available time columns
        time_keys = ['V_t2ms', 'V_t5ms', 'V_t10ms', 'V_t20ms',
                     'V_t50ms', 'V_t100ms', 'V_t200ms', 'V_t280ms']
        time_labels = ['2 ms', '5 ms', '10 ms', '20 ms',
                       '50 ms', '100 ms', '200 ms', '280 ms']
        colors = plt.cm.plasma(np.linspace(0.05, 0.95, len(time_keys)))

        ax_snap = fig.add_subplot(gs[1, :])
        for tk, tl, col in zip(time_keys, time_labels, colors):
            if tk in snap[0]:
                v_cable = [r[tk] for r in snap]
                ax_snap.plot(x_mm, v_cable, color=col, lw=1.2, label=f't = {tl}')
        ax_snap.set_xlabel('Position along cable (mm)')
        ax_snap.set_ylabel('V_m (mV)')
        ax_snap.set_title('Action Potential Propagation — 1D Cable\n'
                          '(τ_f = 40 ms, deterministic, D = 0.1 mm²/ms, N = 100 cells)')
        ax_snap.legend(ncol=4, fontsize=8, loc='upper right')
        ax_snap.axhline(-70, color='grey', linestyle=':', lw=0.8, alpha=0.6)
        ax_snap.annotate('Depolarisation\nwavefront propagates →',
                         xy=(0.12, 0.65), xycoords='axes fraction',
                         fontsize=8.5, color='navy',
                         bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow', alpha=0.7))

    fig.suptitle('1D Cable Tissue Simulation — Pseudo-ECG and AP Propagation\n'
                 '(Monodomain, finite-difference, Plonsey 1964 pseudo-ECG formula)',
                 fontsize=11, fontweight='bold')

    outfile = os.path.join(OUT_DIR, 'fig8_tissue_ecg.png')
    fig.savefig(outfile, bbox_inches='tight')
    plt.close(fig)
    print(f'Saved: {outfile}')


# =============================================================================
# Main
# =============================================================================
def main():
    print("=" * 60)
    print("Sato et al. 2025 — Figure Reproduction")
    print("=" * 60)
    print()

    fig_tauf_sweep()
    fig_u_sweep()
    fig_ap_traces()
    fig_apd_per_beat()
    fig_ca_per_beat()
    fig_stability_boundary()
    fig_summary()
    fig_tissue_variability()
    fig_tissue_ecg()

    print()
    print("All figures saved to figures/")
    print()
    print("Figure index:")
    print("  fig0_summary.png            — Summary of all key findings")
    print("  fig1_stability_boundary.png — Stability boundary (Fig 1)")
    print("  fig2_tauf_sweep.png         — APD bifurcation + variability vs tauf (Fig 2A/4A)")
    print("  fig3_u_sweep.png            — Ca/APD bifurcation + variability vs u (Fig 3/4B/4C)")
    print("  fig4_ap_traces.png          — Action potential traces at different tauf")
    print("  fig5_apd_per_beat.png       — APD vs beat# for selected tauf (Fig 2B)")
    print("  fig6_ca_per_beat.png        — Ca2+ peak vs beat# AP-clamp (Fig 3B)")
    print("  fig7_tissue_variability.png — Tissue vs single-cell APD variability + QTVI")
    print("  fig8_tissue_ecg.png         — Pseudo-ECG traces + cable propagation snapshot")


if __name__ == '__main__':
    main()
