#!/usr/bin/env julia
#=
validate_julia.jl — Cross-validate the Julia Sato-Bers port against C++ reference traces.

PURPOSE:
    Reads CSV reference traces generated by validate_export (C++ ground truth)
    and reproduces the same scenarios using the Julia SatoBers module. Compares
    all 15 state variables at every sample point using float64 tolerances.

VALIDATION SCENARIOS:
    1. Single-beat deterministic trace (equation-level correctness)
    2. Multi-beat convergence (stability across beats)
    3. APD restitution curve (tauf sweep 20–60)
    4. Perturbation tests:
       a. Elevated gk1 conductance (2x, simulating hyperkalemia)
       b. 50% ICaL block (icabar halved)
       c. Enhanced SERCA (2x vup)
       d. Depolarized initial condition (v0 = -60 mV)
    5. Stochastic gating trace (xorshift32 RNG reproducibility)
    6. Steady-state fingerprint (exact match after 500 beats)

TOLERANCES:
    Same as Python validation:
    - Deterministic: rtol=1e-12, atol=1e-12
    - Stochastic: rtol=1e-10, atol=1e-10
    - APD/CaMax: rtol=1e-8, atol=1e-8

USAGE:
    cd <project_root>
    julia validation/validate_julia.jl
=#

# Load the SatoBers module from the julia/ directory
include(joinpath(@__DIR__, "..", "julia", "SatoBers.jl"))
using .SatoBers
using DelimitedFiles

# ============================================================================
# State variable names matching CSV column headers (indices 1–15)
# ============================================================================
const STATE_NAMES = ["v", "ci", "cs", "cj", "cjp", "Ir", "f", "q", "d",
                     "h", "j", "XKr", "XKs", "Xto", "Yto"]

"""
    load_reference_csv(filename) -> (header, data)

Load a C++ reference CSV file. Returns column headers and a Matrix{Float64}
where each row is a time point and columns are [time, v, ci, ..., Yto].
"""
function load_reference_csv(filename::String)
    lines = readlines(filename)
    header = split(lines[1], ',')
    n = length(lines) - 1
    ncol = length(header)
    data = zeros(Float64, n, ncol)
    for i in 1:n
        vals = split(lines[i+1], ',')
        for j in 1:ncol
            data[i, j] = parse(Float64, vals[j])
        end
    end
    return header, data
end

"""
    compare_traces(ref_data, jl_data; rtol=1e-12, atol=1e-12)

Compare reference and Julia state traces element-by-element.
ref_data and jl_data are matrices with columns [time, v, ci, ..., Yto].

Returns (passed, max_abs_err, max_rel_err, worst_info).
"""
function compare_traces(ref_data::Matrix{Float64}, jl_data::Matrix{Float64};
                        rtol=1e-12, atol=1e-12)
    n = min(size(ref_data, 1), size(jl_data, 1))
    if size(ref_data, 1) != size(jl_data, 1)
        println("  WARNING: row count mismatch: ref=$(size(ref_data,1)), jl=$(size(jl_data,1))")
    end

    max_abs = 0.0
    max_rel = 0.0
    worst = ""

    # Compare columns 2–16 (state variables, skip time column 1)
    for i in 1:n
        for j in 2:min(size(ref_data,2), size(jl_data,2))
            ref_val = ref_data[i, j]
            jl_val  = jl_data[i, j]
            abs_err = abs(ref_val - jl_val)
            denom   = max(abs(ref_val), abs(jl_val), 1e-300)
            rel_err = abs_err / denom

            if abs_err > max_abs
                max_abs = abs_err
                if j-1 <= length(STATE_NAMES)
                    worst = "$(STATE_NAMES[j-1]) at row $i (t=$(ref_data[i,1]))"
                end
            end
            max_rel = max(max_rel, rel_err)
        end
    end

    passed = (max_abs < atol) || (max_rel < rtol)
    return passed, max_abs, max_rel, worst
end

"""
    prepace!(u, du, model, beats, bcl, stim, dt; rng=nothing)

Pre-pace the cell model for `beats` beats using Forward Euler.
If `rng` is provided (a StochasticState), stochastic gating is applied.
"""
function prepace!(u, du, model, beats, bcl, stim, dt; rng=nothing)
    BCLn = round(Int, bcl / dt)
    Durn = round(Int, 1.0 / dt)  # 1 ms stimulus duration
    for beat in 1:beats
        for tn in 0:BCLn-1
            if tn < Durn
                cell_rhs_deterministic!(du, u, model, stim)
            else
                cell_rhs_deterministic!(du, u, model, 0.0)
            end
            if rng !== nothing
                stochastic_gate_update!(u, du, dt, model, rng)
            end
            @. u += du * dt
        end
    end
end

"""
    run_beat!(u, du, model, bcl, stim, dt, sample_interval; rng=nothing)

Run one beat and return a matrix of sampled state traces.
Columns: [time, v, ci, cs, ..., Yto] (16 columns total).
"""
function run_beat!(u, du, model, bcl, stim, dt, sample_interval; rng=nothing)
    BCLn = round(Int, bcl / dt)
    Durn = round(Int, 1.0 / dt)
    nsamples = div(BCLn, sample_interval)
    trace = zeros(Float64, nsamples, 16)
    idx = 0
    for tn in 0:BCLn-1
        t = tn * dt
        if mod(tn, sample_interval) == 0
            idx += 1
            if idx <= nsamples
                trace[idx, 1] = t
                trace[idx, 2:16] .= u[1:15]
            end
        end
        if tn < Durn
            cell_rhs_deterministic!(du, u, model, stim)
        else
            cell_rhs_deterministic!(du, u, model, 0.0)
        end
        if rng !== nothing
            stochastic_gate_update!(u, du, dt, model, rng)
        end
        @. u += du * dt
    end
    return trace[1:idx, :]
end

# ============================================================================
# Scenario runners
# ============================================================================

"""
    scenario1() -> Bool

Scenario 1: Single-beat deterministic trace.
N_CaL=0, tauf=30, 100-beat prepace, 1 beat recorded at 0.5 ms resolution.
"""
function scenario1()
    println("Scenario 1: Single beat deterministic trace")
    model = SatoBersModel{Float64}(tauf=30.0, av=3.0, N_CaL=0)
    dt = 0.05; stim = 50.0; bcl = 300.0
    u  = collect(default_initial_state(model))
    du = zeros(15)

    prepace!(u, du, model, 100, bcl, stim, dt)
    trace = run_beat!(u, du, model, bcl, stim, dt, 10)

    _, ref = load_reference_csv("validation/reference/scenario1_single_beat.csv")
    passed, max_abs, max_rel, worst = compare_traces(ref, trace)
    status = passed ? "PASS" : "FAIL"
    println("  $status: max_abs_err=$(round(max_abs, sigdigits=3)), max_rel_err=$(round(max_rel, sigdigits=3))")
    !passed && println("  Worst: $worst")
    return passed
end

"""
    scenario2() -> Bool

Scenario 2: Multi-beat convergence trace (10 beats, sampled every 20 steps).
"""
function scenario2()
    println("Scenario 2: Multi-beat convergence trace")
    model = SatoBersModel{Float64}(tauf=30.0, av=3.0, N_CaL=0)
    dt = 0.05; stim = 50.0; bcl = 300.0
    u  = collect(default_initial_state(model))
    du = zeros(15)

    prepace!(u, du, model, 100, bcl, stim, dt)

    # Record 10 beats
    BCLn = round(Int, bcl / dt)
    Durn = round(Int, 1.0 / dt)
    total = 10 * BCLn
    nsamples = div(total, 20)
    trace = zeros(Float64, nsamples, 16)
    idx = 0
    for tn in 0:total-1
        t = tn * dt
        if mod(tn, 20) == 0
            idx += 1
            if idx <= nsamples
                trace[idx, 1] = t
                trace[idx, 2:16] .= u[1:15]
            end
        end
        if mod(tn, BCLn) < Durn
            cell_rhs_deterministic!(du, u, model, stim)
        else
            cell_rhs_deterministic!(du, u, model, 0.0)
        end
        @. u += du * dt
    end
    trace = trace[1:idx, :]

    _, ref = load_reference_csv("validation/reference/scenario2_multi_beat.csv")
    passed, max_abs, max_rel, worst = compare_traces(ref, trace)
    status = passed ? "PASS" : "FAIL"
    println("  $status: max_abs_err=$(round(max_abs, sigdigits=3)), max_rel_err=$(round(max_rel, sigdigits=3))")
    !passed && println("  Worst: $worst")
    return passed
end

"""
    scenario3() -> Bool

Scenario 3: APD restitution — tauf sweep 20–60, 200-beat prepace + 100-beat measurement.
Compares APD and peak Ca²⁺ per beat.
"""
function scenario3()
    println("Scenario 3: APD restitution (tauf sweep 20-60)")
    dt = 0.05; stim = 50.0; vc = -70.0
    u  = zeros(15)
    du = zeros(15)

    # Initialize state to defaults
    u .= collect(default_initial_state(SatoBersModel{Float64}()))

    jl_results = Vector{NTuple{3,Float64}}()

    for tf in 20:60
        model = SatoBersModel{Float64}(tauf=Float64(tf), av=3.0, N_CaL=0)
        bcl = 300.0
        BCLn = round(Int, bcl / dt)
        Durn = round(Int, 1.0 / dt)

        # Pre-pace 200 beats
        prepace!(u, du, model, 200, bcl, stim, dt)

        # Measure 100 beats
        Tn = 100 * BCLn
        first = false
        cimax = 0.0; apd = 0.0; vold = u[1]; APDt1 = 0.0

        for tn in 0:Tn-1
            t = tn * dt
            if mod(tn, BCLn) < Durn
                if first
                    first = false
                    push!(jl_results, (Float64(tf), apd, cimax))
                    cimax = 0.0; apd = 0.0
                end
                cell_rhs_deterministic!(du, u, model, stim)
            else
                first = true
                cell_rhs_deterministic!(du, u, model, 0.0)
            end
            @. u += du * dt
            if cimax < u[2]
                cimax = u[2]
            end
            if vold < vc && u[1] > vc
                APDt1 = (t - dt) + dt * (vc - vold) / (u[1] - vold)
            elseif vold > vc && u[1] < vc
                APDt2 = (t - dt) + dt * (vc - vold) / (u[1] - vold)
                apd = APDt2 - APDt1
            end
            vold = u[1]
        end
    end

    # Compare
    _, ref = load_reference_csv("validation/reference/scenario3_apd_restitution.csv")
    n = min(size(ref, 1), length(jl_results))
    max_apd_err = 0.0; max_ci_err = 0.0
    for i in 1:n
        apd_err = abs(ref[i, 2] - jl_results[i][2])
        ci_err  = abs(ref[i, 3] - jl_results[i][3])
        max_apd_err = max(max_apd_err, apd_err)
        max_ci_err  = max(max_ci_err,  ci_err)
    end

    passed = max_apd_err < 1e-8 && max_ci_err < 1e-8
    status = passed ? "PASS" : "FAIL"
    println("  $status: max_apd_err=$(round(max_apd_err, sigdigits=3)), max_cimax_err=$(round(max_ci_err, sigdigits=3))")
    println("  Compared $n beat measurements across tauf=20-60")
    return passed
end

"""
    scenario4_helper(name, ref_file, model) -> Bool

Helper for perturbation tests. Pre-paces 100 beats, records 1 beat, compares.
"""
function scenario4_helper(name, ref_file, model)
    dt = 0.05; stim = 50.0; bcl = 300.0
    u  = collect(default_initial_state(model))
    du = zeros(15)

    prepace!(u, du, model, 100, bcl, stim, dt)
    trace = run_beat!(u, du, model, bcl, stim, dt, 10)

    _, ref = load_reference_csv(ref_file)
    passed, max_abs, max_rel, worst = compare_traces(ref, trace, rtol=1e-11, atol=1e-11)
    status = passed ? "PASS" : "FAIL"
    println("  $name: $status (max_abs=$(round(max_abs, sigdigits=3)), max_rel=$(round(max_rel, sigdigits=3)))")
    !passed && println("    Worst: $worst")
    return passed
end

"""
    scenario4() -> Bool

Scenario 4: Perturbation tests.
4a: 2x gk1, 4b: 50% ICaL, 4c: 2x SERCA, 4d: depolarized start.
"""
function scenario4()
    println("Scenario 4: Perturbation tests")
    r = Bool[]
    push!(r, scenario4_helper("4a: 2x gk1",
        "validation/reference/scenario4a_elevated_gk1.csv",
        SatoBersModel{Float64}(tauf=30.0, av=3.0, N_CaL=0, gk1=5.6)))
    push!(r, scenario4_helper("4b: 50% ICaL block",
        "validation/reference/scenario4b_ical_block.csv",
        SatoBersModel{Float64}(tauf=30.0, av=3.0, N_CaL=0, icabar=1.75)))
    push!(r, scenario4_helper("4c: 2x SERCA",
        "validation/reference/scenario4c_enhanced_serca.csv",
        SatoBersModel{Float64}(tauf=30.0, av=3.0, N_CaL=0, vup=0.500)))

    # 4d: Depolarized start — modify initial state
    model_d = SatoBersModel{Float64}(tauf=30.0, av=3.0, N_CaL=0)
    dt = 0.05; stim = 50.0; bcl = 300.0
    u  = collect(default_initial_state(model_d))
    u[1] = -60.0  # Depolarized initial condition
    du = zeros(15)
    prepace!(u, du, model_d, 100, bcl, stim, dt)
    trace = run_beat!(u, du, model_d, bcl, stim, dt, 10)
    _, ref = load_reference_csv("validation/reference/scenario4d_depolarized.csv")
    passed, max_abs, max_rel, worst = compare_traces(ref, trace, rtol=1e-11, atol=1e-11)
    status = passed ? "PASS" : "FAIL"
    println("  4d: v0=-60mV: $status (max_abs=$(round(max_abs, sigdigits=3)), max_rel=$(round(max_rel, sigdigits=3)))")
    !passed && println("    Worst: $worst")
    push!(r, passed)

    return all(r)
end

"""
    scenario5() -> Bool

Scenario 5: Stochastic gating trace with fixed xorshift32 seed.
Tests RNG reproducibility across C++ and Julia.
"""
function scenario5()
    println("Scenario 5: Stochastic gating (fixed seed)")
    model = SatoBersModel{Float64}(tauf=30.0, av=3.0, N_CaL=100000)
    dt = 0.05; stim = 50.0; bcl = 300.0
    u   = collect(default_initial_state(model))
    du  = zeros(15)
    rng = StochasticState(UInt32(1821800813))

    prepace!(u, du, model, 50, bcl, stim, dt; rng=rng)
    trace = run_beat!(u, du, model, bcl, stim, dt, 10; rng=rng)

    _, ref = load_reference_csv("validation/reference/scenario5_stochastic.csv")
    passed, max_abs, max_rel, worst = compare_traces(ref, trace, rtol=1e-10, atol=1e-10)
    status = passed ? "PASS" : "FAIL"
    println("  $status: max_abs_err=$(round(max_abs, sigdigits=3)), max_rel_err=$(round(max_rel, sigdigits=3))")
    !passed && println("  Worst: $worst")
    return passed
end

"""
    scenario6() -> Bool

Scenario 6: Steady-state fingerprint after 500 beats (deterministic).
"""
function scenario6()
    println("Scenario 6: Steady-state fingerprint (500 beats)")
    model = SatoBersModel{Float64}(tauf=30.0, av=3.0, N_CaL=0)
    dt = 0.05; stim = 50.0; bcl = 300.0
    u  = collect(default_initial_state(model))
    du = zeros(15)

    prepace!(u, du, model, 500, bcl, stim, dt)

    # Single-point trace
    jl_data = zeros(Float64, 1, 16)
    jl_data[1, 1] = 0.0
    jl_data[1, 2:16] .= u[1:15]

    _, ref = load_reference_csv("validation/reference/scenario6_steady_state.csv")
    passed, max_abs, max_rel, worst = compare_traces(ref, jl_data)
    status = passed ? "PASS" : "FAIL"
    println("  $status: max_abs_err=$(round(max_abs, sigdigits=3)), max_rel_err=$(round(max_rel, sigdigits=3))")
    !passed && println("  Worst: $worst")
    return passed
end

# ============================================================================
# Main — run all scenarios
# ============================================================================
function main()
    println("=" ^ 60)
    println("Sato-Bers Model: Julia Validation Suite")
    println("=" ^ 60)
    println()

    results = Dict{String, Bool}()
    results["scenario1"] = scenario1(); println()
    results["scenario2"] = scenario2(); println()
    results["scenario3"] = scenario3(); println()
    results["scenario4"] = scenario4(); println()
    results["scenario5"] = scenario5(); println()
    results["scenario6"] = scenario6()

    println()
    println("=" ^ 60)
    println("SUMMARY")
    println("=" ^ 60)
    all_passed = true
    for (name, passed) in sort(collect(results))
        status = passed ? "PASS" : "FAIL"
        println("  $name: $status")
        if !passed
            all_passed = false
        end
    end
    println()
    if all_passed
        println("ALL SCENARIOS PASSED")
    else
        println("SOME SCENARIOS FAILED — see details above")
    end
    return all_passed ? 0 : 1
end

exit(main())
