#!/usr/bin/env python3
"""
validate_python.py — Cross-validate the Python Sato-Bers port against C++ reference traces.

PURPOSE:
    Reads CSV reference traces generated by validate_export (C++ ground truth)
    and reproduces the same scenarios using the Python Cell class. Compares all
    15 state variables at every sample point using float64 tolerances.

VALIDATION SCENARIOS:
    1. Single-beat deterministic trace (equation-level correctness)
    2. Multi-beat convergence (stability across beats)
    3. APD restitution curve (tauf sweep 20–60)
    4. Perturbation tests:
       a. Elevated gk1 conductance (2x, simulating hyperkalemia)
       b. 50% ICaL block (icabar halved)
       c. Enhanced SERCA (2x vup)
       d. Depolarized initial condition (v0 = -60 mV)
    5. Stochastic gating trace (xorshift32 RNG reproducibility)
    6. Steady-state fingerprint (exact match after 500 beats)

TOLERANCES:
    - Deterministic scenarios: rtol=1e-12, atol=1e-12 (bit-level agreement expected)
    - Stochastic scenario: rtol=1e-10, atol=1e-10 (minor float rounding in RNG)
    - APD/CaMax: rtol=1e-8, atol=1e-8 (accumulated integration differences)

OUTPUT:
    Prints PASS/FAIL for each scenario with max absolute/relative error.
    Also writes Python traces to validation/results/ for manual inspection.

USAGE:
    cd validation
    python validate_python.py
"""

import sys
import os
import csv
import math
import numpy as np

# Add parent python/ directory to path so we can import the Cell class
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'python'))
from cell import Cell, xorshift

# ============================================================================
# Constants: state variable names matching CSV column headers
# ============================================================================
STATE_NAMES = ['v', 'ci', 'cs', 'cj', 'cjp', 'Ir', 'f', 'q', 'd', 'h', 'j',
               'XKr', 'XKs', 'Xto', 'Yto']


def load_reference_csv(filename):
    """
    Load a C++ reference CSV file into a list of dicts.

    Each row becomes a dict with keys: 'time', 'v', 'ci', 'cs', ..., 'Yto'.
    All values are parsed as float64. Raises FileNotFoundError if the
    reference data hasn't been generated yet.

    Parameters
    ----------
    filename : str
        Path to the CSV file relative to the current working directory.

    Returns
    -------
    list of dict
        Each dict maps column names to float64 values.
    """
    rows = []
    with open(filename, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append({k: float(v) for k, v in row.items()})
    return rows


def get_cell_state_dict(cell):
    """
    Extract the 15 state variables from a Cell object as a dict.

    This provides a convenient way to compare the Python cell state
    against reference CSV rows column-by-column.

    Parameters
    ----------
    cell : Cell
        The Python cell model instance.

    Returns
    -------
    dict
        Maps state variable names to their current float64 values.
    """
    return {
        'v': cell.v, 'ci': cell.ci, 'cs': cell.cs, 'cj': cell.cj, 'cjp': cell.cjp,
        'Ir': cell.Ir, 'f': cell.f, 'q': cell.q, 'd': cell.d,
        'h': cell.h, 'j': cell.j, 'XKr': cell.XKr, 'XKs': cell.XKs,
        'Xto': cell.Xto, 'Yto': cell.Yto
    }


def compare_traces(ref_rows, py_rows, rtol=1e-12, atol=1e-12):
    """
    Compare reference (C++) and Python state traces element-by-element.

    For each (time, variable) pair, computes the absolute difference and
    the relative difference (using max(|ref|, |py|) as denominator).
    Reports the worst-case error across all points and variables.

    Parameters
    ----------
    ref_rows : list of dict
        C++ reference trace from load_reference_csv().
    py_rows : list of dict
        Python trace collected during simulation.
    rtol : float
        Relative tolerance. Comparison passes if |ref-py|/max(|ref|,|py|) < rtol.
    atol : float
        Absolute tolerance. Comparison passes if |ref-py| < atol.

    Returns
    -------
    tuple (bool, float, float, str)
        (passed, max_abs_err, max_rel_err, worst_variable)
    """
    max_abs = 0.0
    max_rel = 0.0
    worst_var = ""

    # Compare row counts — length mismatch is an immediate failure
    if len(ref_rows) != len(py_rows):
        print(f"  WARNING: row count mismatch: ref={len(ref_rows)}, py={len(py_rows)}")
        n = min(len(ref_rows), len(py_rows))
    else:
        n = len(ref_rows)

    for i in range(n):
        for name in STATE_NAMES:
            ref_val = ref_rows[i][name]
            py_val = py_rows[i][name]
            abs_err = abs(ref_val - py_val)
            denom = max(abs(ref_val), abs(py_val), 1e-300)
            rel_err = abs_err / denom

            if abs_err > max_abs:
                max_abs = abs_err
                if abs_err > max_rel:
                    worst_var = f"{name} at row {i} (t={ref_rows[i].get('time', '?')})"
            if rel_err > max_rel:
                max_rel = rel_err

    passed = (max_abs < atol) or (max_rel < rtol)
    return passed, max_abs, max_rel, worst_var


def run_cell_beat(cell, bcl, stim, dt, sample_interval=10):
    """
    Run the cell model for one full beat and collect sampled state traces.

    Applies stimulus during the first STIM_DURATION ms of the beat cycle,
    then free-runs for the remainder. Samples state every `sample_interval` steps.

    Parameters
    ----------
    cell : Cell
        Cell model instance (already pre-paced to desired state).
    bcl : float
        Basic cycle length in ms.
    stim : float
        Stimulus current amplitude.
    dt : float
        Integration time step in ms.
    sample_interval : int
        Record state every this many time steps.

    Returns
    -------
    list of dict
        Sampled state trace with 'time' and all 15 state variable keys.
    """
    BCLn = int(bcl / dt)
    Durn = int(Cell.STIM_DURATION / dt)
    trace = []
    for tn in range(BCLn):
        t = tn * dt
        if tn % sample_interval == 0:
            row = {'time': t}
            row.update(get_cell_state_dict(cell))
            trace.append(row)
        if tn < Durn:
            cell.pace(stim)
        else:
            cell.pace()
    return trace


def prepace(cell, beats, bcl, stim, dt):
    """
    Pre-pace the cell model for a given number of beats.

    Pre-pacing drives the model toward its limit-cycle attractor
    from arbitrary initial conditions, ensuring subsequent measurements
    reflect steady-state behavior rather than transient dynamics.

    Parameters
    ----------
    cell : Cell
        Cell model instance.
    beats : int
        Number of pre-pacing beats.
    bcl : float
        Basic cycle length in ms.
    stim : float
        Stimulus current amplitude.
    dt : float
        Integration time step.
    """
    BCLn = int(bcl / dt)
    Durn = int(Cell.STIM_DURATION / dt)
    for beat in range(beats):
        for tn in range(BCLn):
            if tn < Durn:
                cell.pace(stim)
            else:
                cell.pace()


def save_trace_csv(trace, filename):
    """
    Write a state trace to a CSV file for manual inspection / plotting.

    Parameters
    ----------
    trace : list of dict
        State trace as returned by run_cell_beat().
    filename : str
        Output CSV file path.
    """
    if not trace:
        return
    with open(filename, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=['time'] + STATE_NAMES)
        writer.writeheader()
        for row in trace:
            writer.writerow({k: f"{row[k]:.17g}" for k in ['time'] + STATE_NAMES})


# ============================================================================
# Scenario runners — each reproduces the corresponding C++ validation scenario
# ============================================================================

def scenario1():
    """
    Scenario 1: Single-beat deterministic trace.

    Reproduces C++ scenario with N_CaL=0, tauf=30, 100-beat prepace,
    then records one beat at 0.5 ms resolution (every 10 steps).
    """
    print("Scenario 1: Single beat deterministic trace")
    cell = Cell()
    cell.N_CaL = 0
    cell.tauf = 30
    cell.av = 3.0
    dt = cell.dt
    stim = Cell.STIM
    bcl = 300.0

    prepace(cell, 100, bcl, stim, dt)
    trace = run_cell_beat(cell, bcl, stim, dt, sample_interval=10)
    save_trace_csv(trace, "validation/results/scenario1_python.csv")

    ref = load_reference_csv("validation/reference/scenario1_single_beat.csv")
    passed, max_abs, max_rel, worst = compare_traces(ref, trace)
    status = "PASS" if passed else "FAIL"
    print(f"  {status}: max_abs_err={max_abs:.3e}, max_rel_err={max_rel:.3e}")
    if not passed:
        print(f"  Worst: {worst}")
    return passed


def scenario2():
    """
    Scenario 2: Multi-beat convergence trace (10 beats after 100-beat prepace).

    Verifies no numerical drift across beats. Samples every 20 steps = 1.0 ms.
    """
    print("Scenario 2: Multi-beat convergence trace")
    cell = Cell()
    cell.N_CaL = 0
    cell.tauf = 30
    cell.av = 3.0
    dt = cell.dt
    stim = Cell.STIM
    bcl = 300.0

    prepace(cell, 100, bcl, stim, dt)

    # Record 10 beats
    BCLn = int(bcl / dt)
    Durn = int(Cell.STIM_DURATION / dt)
    total_steps = 10 * BCLn
    trace = []
    for tn in range(total_steps):
        t = tn * dt
        if tn % 20 == 0:
            row = {'time': t}
            row.update(get_cell_state_dict(cell))
            trace.append(row)
        if tn % BCLn < Durn:
            cell.pace(stim)
        else:
            cell.pace()

    save_trace_csv(trace, "validation/results/scenario2_python.csv")
    ref = load_reference_csv("validation/reference/scenario2_multi_beat.csv")
    passed, max_abs, max_rel, worst = compare_traces(ref, trace)
    status = "PASS" if passed else "FAIL"
    print(f"  {status}: max_abs_err={max_abs:.3e}, max_rel_err={max_rel:.3e}")
    if not passed:
        print(f"  Worst: {worst}")
    return passed


def scenario3():
    """
    Scenario 3: APD restitution — tauf sweep from 20 to 60.

    Compares APD and CaMax values per beat across the entire tauf range.
    Uses 200-beat prepace + 100-beat measurement per tauf (matching C++ reference).
    """
    print("Scenario 3: APD restitution (tauf sweep 20-60)")
    cell = Cell()
    cell.N_CaL = 0
    cell.av = 3.0
    dt = cell.dt
    stim = Cell.STIM
    vc = Cell.VC

    py_results = []
    for tf in range(20, 61):
        cell.tauf = float(tf)
        bcl = 300.0
        BCLn = int(bcl / dt)
        Durn = int(Cell.STIM_DURATION / dt)

        # Pre-pace 200 beats
        prepace_Tn = 200 * BCLn
        for tn in range(prepace_Tn):
            if tn % BCLn < Durn:
                cell.pace(stim)
            else:
                cell.pace()

        # Measure 100 beats
        measure_Tn = 100 * BCLn
        first = False
        cimax = 0.0
        apd = 0.0
        vold = cell.v
        APDt1 = 0.0
        for tn in range(measure_Tn):
            t = tn * dt
            if tn % BCLn < Durn:
                if first:
                    first = False
                    py_results.append({'tauf': tf, 'apd': apd, 'cimax': cimax})
                    cimax = 0.0
                    apd = 0.0
                cell.pace(stim)
            else:
                first = True
                cell.pace()
            if cimax < cell.ci:
                cimax = cell.ci
            if vold < vc and cell.v > vc:
                APDt1 = (t - dt) + dt * (vc - vold) / (cell.v - vold)
            elif vold > vc and cell.v < vc:
                APDt2 = (t - dt) + dt * (vc - vold) / (cell.v - vold)
                apd = APDt2 - APDt1
            vold = cell.v

    # Compare against reference
    ref = load_reference_csv("validation/reference/scenario3_apd_restitution.csv")

    # Compare APD and cimax values
    n = min(len(ref), len(py_results))
    max_apd_err = 0.0
    max_ci_err = 0.0
    for i in range(n):
        apd_err = abs(ref[i]['apd'] - py_results[i]['apd'])
        ci_err = abs(ref[i]['cimax'] - py_results[i]['cimax'])
        max_apd_err = max(max_apd_err, apd_err)
        max_ci_err = max(max_ci_err, ci_err)

    passed = max_apd_err < 1e-8 and max_ci_err < 1e-8
    status = "PASS" if passed else "FAIL"
    print(f"  {status}: max_apd_err={max_apd_err:.3e}, max_cimax_err={max_ci_err:.3e}")
    print(f"  Compared {n} beat measurements across tauf={20}-{60}")
    return passed


def scenario4_helper(name, ref_file, configure_fn):
    """
    Generic helper for perturbation tests.

    Creates a cell, applies the configure_fn to set perturbation parameters,
    pre-paces for 100 beats, records 1 beat, and compares against reference.

    Parameters
    ----------
    name : str
        Human-readable scenario name for display.
    ref_file : str
        Path to the C++ reference CSV.
    configure_fn : callable
        Function that takes a Cell and modifies it (e.g., cell.gk1 = 5.6).

    Returns
    -------
    bool
        True if scenario passed, False otherwise.
    """
    cell = Cell()
    cell.N_CaL = 0
    cell.tauf = 30
    cell.av = 3.0
    configure_fn(cell)
    dt = cell.dt
    stim = Cell.STIM
    bcl = 300.0

    prepace(cell, 100, bcl, stim, dt)
    trace = run_cell_beat(cell, bcl, stim, dt, sample_interval=10)

    ref = load_reference_csv(ref_file)
    passed, max_abs, max_rel, worst = compare_traces(ref, trace, rtol=1e-11, atol=1e-11)
    status = "PASS" if passed else "FAIL"
    print(f"  {name}: {status} (max_abs={max_abs:.3e}, max_rel={max_rel:.3e})")
    if not passed:
        print(f"    Worst: {worst}")
    return passed


def scenario4():
    """
    Scenario 4: Perturbation tests — verify identical response to parameter changes.

    4a: Doubled gk1 (simulates hyperkalemia effect on IK1)
    4b: 50% ICaL block (icabar = 1.75)
    4c: Enhanced SERCA (vup = 0.500)
    4d: Depolarized start (v = -60 mV)
    """
    print("Scenario 4: Perturbation tests")
    results = []
    results.append(scenario4_helper("4a: 2x gk1",
        "validation/reference/scenario4a_elevated_gk1.csv",
        lambda c: setattr(c, 'gk1', 5.6)))
    results.append(scenario4_helper("4b: 50% ICaL block",
        "validation/reference/scenario4b_ical_block.csv",
        lambda c: setattr(c, 'icabar', 1.75)))
    results.append(scenario4_helper("4c: 2x SERCA",
        "validation/reference/scenario4c_enhanced_serca.csv",
        lambda c: setattr(c, 'vup', 0.500)))
    results.append(scenario4_helper("4d: v0=-60mV",
        "validation/reference/scenario4d_depolarized.csv",
        lambda c: setattr(c, 'v', -60.0)))
    return all(results)


def scenario5():
    """
    Scenario 5: Stochastic gating trace — xorshift32 RNG reproducibility.

    The stochastic gating uses a Langevin equation with noise from
    Box-Muller transform of xorshift32 uniform variates. The Python
    xorshift implementation must produce identical bit patterns as C++.

    Uses slightly relaxed tolerance (1e-10) since stochastic mode
    may amplify small float64 rounding differences over 50 pre-pace beats.
    """
    print("Scenario 5: Stochastic gating (fixed seed)")
    cell = Cell()
    cell.N_CaL = 100000
    cell.tauf = 30
    cell.av = 3.0
    cell.xsx = 1821800813
    dt = cell.dt
    stim = Cell.STIM
    bcl = 300.0

    prepace(cell, 50, bcl, stim, dt)
    trace = run_cell_beat(cell, bcl, stim, dt, sample_interval=10)
    save_trace_csv(trace, "validation/results/scenario5_python.csv")

    ref = load_reference_csv("validation/reference/scenario5_stochastic.csv")
    passed, max_abs, max_rel, worst = compare_traces(ref, trace, rtol=1e-10, atol=1e-10)
    status = "PASS" if passed else "FAIL"
    print(f"  {status}: max_abs_err={max_abs:.3e}, max_rel_err={max_rel:.3e}")
    if not passed:
        print(f"  Worst: {worst}")
    return passed


def scenario6():
    """
    Scenario 6: Steady-state fingerprint — exact match after 500 beats.

    After 500 beats of pre-pacing, the model should be deeply converged
    to its limit cycle. The final state is a single-point "fingerprint"
    that must match the C++ reference to near machine precision.
    """
    print("Scenario 6: Steady-state fingerprint (500 beats)")
    cell = Cell()
    cell.N_CaL = 0
    cell.tauf = 30
    cell.av = 3.0
    dt = cell.dt
    stim = Cell.STIM
    bcl = 300.0

    prepace(cell, 500, bcl, stim, dt)

    py_row = {'time': 0.0}
    py_row.update(get_cell_state_dict(cell))
    ref = load_reference_csv("validation/reference/scenario6_steady_state.csv")
    passed, max_abs, max_rel, worst = compare_traces(ref, [py_row])
    status = "PASS" if passed else "FAIL"
    print(f"  {status}: max_abs_err={max_abs:.3e}, max_rel_err={max_rel:.3e}")
    if not passed:
        print(f"  Worst: {worst}")
    return passed


# ============================================================================
# Main entry point — run all scenarios and report summary
# ============================================================================
def main():
    """
    Execute all validation scenarios and print a summary report.

    Returns exit code 0 if all scenarios pass, 1 otherwise.
    """
    print("=" * 60)
    print("Sato-Bers Model: Python Validation Suite")
    print("=" * 60)
    print()

    results = {}
    results['scenario1'] = scenario1()
    print()
    results['scenario2'] = scenario2()
    print()
    results['scenario3'] = scenario3()
    print()
    results['scenario4'] = scenario4()
    print()
    results['scenario5'] = scenario5()
    print()
    results['scenario6'] = scenario6()

    # Summary
    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    all_passed = True
    for name, passed in results.items():
        status = "PASS" if passed else "FAIL"
        print(f"  {name}: {status}")
        if not passed:
            all_passed = False

    print()
    if all_passed:
        print("ALL SCENARIOS PASSED")
        return 0
    else:
        print("SOME SCENARIOS FAILED — see details above")
        return 1


if __name__ == "__main__":
    sys.exit(main())
